# Smart Water Treatment

## Phase 1 — Data Understanding

Author: Hamid Saeli

---

### Objective

Understand the SWaT dataset before building any Machine Learning model.

The purpose of this notebook is to:

- Understand the industrial process
- Identify sensors and actuators
- Explore dataset structure
- Prepare for data cleaning

In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
df = pd.read_csv("../data/raw/merged.csv")

In [3]:
df.head()

,Timestamp,FIT101,LIT101,MV101,P101,P102,AIT201,AIT202,AIT203,FIT201,MV201,P201,P202,P203,P204,P205,P206,DPIT301,FIT301,LIT301,MV301,MV302,MV303,MV304,P301,P302,AIT401,AIT402,FIT401,LIT401,P401,P402,P403,P404,UV401,AIT501,AIT502,AIT503,AIT504,FIT501,FIT502,FIT503,FIT504,P501,P502,PIT501,PIT502,PIT503,FIT601,P601,P602,P603,Normal/Attack
0,28/12/2015 10:00:00 AM,2.427057,522.8467,2.0,2,1,262.0161,8.396437,328.6337,2.445391,2.0,1.0,1.0,2,1.0,2,1,19.74838,2.206835,956.1651,1,2,1.0,1,1,2,148.808,156.0882,1.713517,942.0662,1,2,1,1,2,7.878621,145.1166,264.5475,12.03538,1.723789,1.279621,0.735269,0.307786,2,1,250.8652,1.649953,189.5988,0.000128,1,1,1,Normal
1,28/12/2015 10:00:01 AM,2.446274,522.8860,2.0,2,1,262.0161,8.396437,328.6337,2.445391,2.0,1.0,1.0,2,1.0,2,1,19.74838,2.208244,956.1651,1,2,1.0,1,1,2,148.808,156.0882,1.715952,942.0277,1,2,1,1,2,7.878621,145.1166,264.5475,12.03538,1.723789,1.297554,0.735269,0.307786,2,1,250.8652,1.649953,189.6789,0.000128,1,1,1,Normal
2,28/12/2015 10:00:02 AM,2.489191,522.8467,2.0,2,1,262.0161,8.394514,328.6337,2.442316,2.0,1.0,1.0,2,1.0,2,1,19.69076,2.208628,956.4855,1,2,1.0,1,1,2,148.808,156.0882,1.715952,941.8739,1,2,1,1,2,7.878621,145.1166,264.5475,12.03538,1.723404,1.293967,0.735269,0.308619,2,1,250.8812,1.649953,189.6789,0.000128,1,1,1,Normal
3,28/12/2015 10:00:03 AM,2.534350,522.9645,2.0,2,1,262.0161,8.394514,328.6337,2.442316,2.0,1.0,1.0,2,1.0,2,1,19.69076,2.208628,956.8060,1,2,1.0,1,1,2,148.808,156.0882,1.714670,941.7970,1,2,1,1,2,7.878621,145.0141,264.5475,12.03538,1.723404,1.281158,0.735269,0.308619,2,1,250.8812,1.649953,189.6148,0.000128,1,1,1,Normal
4,28/12/2015 10:00:04 AM,2.569260,523.4748,2.0,2,1,262.0161,8.394514,328.6337,2.443085,2.0,1.0,1.0,2,1.0,2,1,19.69076,2.208628,957.0864,1,2,1.0,1,1,2,148.808,156.0882,1.714670,942.2200,1,2,1,1,2,7.878621,144.8859,264.5475,12.03538,1.723404,1.281158,0.735269,0.308619,2,1,250.8812,1.649953,189.5027,0.000128,1,1,1,Normal

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1441719
Columns: 53

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1441719 entries, 0 to 1441718
Data columns (total 53 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0    Timestamp     1441719 non-null  object
 1   FIT101         1441719 non-null  float64
 2   LIT101         1441719 non-null  float64
 3    MV101         449919 non-null   float64
 4   P101           1441719 non-null  int64
 5   P102           1441719 non-null  int64
 6    AIT201        449919 non-null   float64
 7   AIT202         1441719 non-null  float64
 8   AIT203         1441719 non-null  float64
 9   FIT201         1441719 non-null  float64
 10   MV201         449919 non-null   float64
 11   P201          449919 non-null   float64
 12   P202          449919 non-null   float64
 13  P203           1441719 non-null  int64
 14   P204          449919 non-null   float64
 15  P205           1441719 non-null  int64
 16  P206           1441719 non-null  int64
 17  DPIT301        1441719 non-null  float64
 18  FIT301         1441719 non-null  float64
 19  LIT301         1441719 non-null  float64
 20  MV301          1441719 non-null  int64
 21  MV302          1441719 non-null  int64
 22   MV303         449919 non-null   float64
 23  MV304          1441719 non-null  int64
 24  P301           1441719 non-null  int64
 25  P302           1441719 non-null  int64
 26  AIT401         1441719 non-null  float64
 27  AIT402         1441719 non-null  float64
 28  FIT401         1441719 non-null  float64
 29  LIT401         1441719 non-null  float64
 30  P401           1441719 non-null  int64
 31  P402           1441719 non-null  int64
 32  P403           1441719 non-null  int64
 33  P404           1441719 non-null  int64
 34  UV401          1441719 non-null  int64
 35  AIT501         1441719 non-null  float64
 36  AIT502         1441719 non-null  float64
 37  AIT503         1441719 non-null  float64
 38  AIT504         1441719 non-null  float64
 39  FIT501         1441719 non-null  float64
 40  FIT502         1441719 non-null  float64
 41  FIT503         1441719 non-null  float64
 42  FIT504         1441719 non-null  float64
 43  P501           1441719 non-null  int64
 44  P502           1441719 non-null  int64
 45  PIT501         1441719 non-null  float64
 46  PIT502         1441719 non-null  float64
 47  PIT503         1441719 non-null  float64
 48  FIT601         1441719 non-null  float64
 49  P601           1441719 non-null  int64
 50  P602           1441719 non-null  int64
 51  P603           1441719 non-null  int64
 52  Normal/Attack  1441719 non-null  object
dtypes: float64(31), int64(20), object(2)
memory usage: 583.0+ MB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
FIT101,1441719.0,1.806108,1.153932,0.000000,0.000000,2.487269,2.588156,2.760145
LIT101,1441719.0,593.120048,123.932458,120.623700,508.794300,526.811300,695.715900,1000.000000
MV101,449919.0,1.665335,0.482323,0.000000,1.000000,2.000000,2.000000,2.000000
P101,1441719.0,1.730916,0.443484,1.000000,1.000000,2.000000,2.000000,2.000000
P102,1441719.0,1.002168,0.046507,1.000000,1.000000,1.000000,1.000000,2.000000
AIT201,449919.0,210.297302,35.157909,168.033800,177.102000,193.508100,253.845200,267.719800
AIT202,1441719.0,8.431862,0.118139,6.000000,8.357024,8.380095,8.450590,8.988273
AIT203,1441719.0,339.565826,43.999077,285.337100,321.148400,330.017900,334.145100,567.469900
FIT201,1441719.0,1.791239,1.084655,0.000000,0.000000,2.444238,2.452440,2.826899
MV201,449919.0,1.691584,0.470611,0.000000,1.000000,2.000000,2.000000,2.000000
P201,449919.0,1.121068,0.326207,1.000000,1.000000,1.000000,1.000000,2.000000
P202,449919.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
P203,1441719.0,1.728808,0.444575,1.000000,1.000000,2.000000,2.000000,2.000000
P204,449919.0,1.000124,0.011156,1.000000,1.000000,1.000000,1.000000,2.000000
P205,1441719.0,1.670107,0.470174,1.000000,1.000000,2.000000,2.000000,2.000000
P206,1441719.0,1.000038,0.006176,1.000000,1.000000,1.000000,1.000000,2.000000
DPIT301,1441719.0,16.347187,7.081101,0.000000,19.543500,19.847620,20.020490,45.000000
FIT301,1441719.0,1.796686,0.852411,0.000000,2.198379,2.210678,2.216058,2.376197
LIT301,1441719.0,902.258604,93.084535,132.818500,834.681800,920.437100,968.141200,1201.000000
MV301,1441719.0,1.006075,0.114535,0.000000,1.000000,1.000000,1.000000,2.000000
MV302,1441719.0,1.784742,0.426884,0.000000,2.000000,2.000000,2.000000,2.000000
MV303,449919.0,1.023349,0.181441,0.000000,1.000000,1.000000,1.000000,2.000000
MV304,1441719.0,1.048570,0.245753,0.000000,1.000000,1.000000,1.000000,2.000000
P301,1441719.0,1.002601,0.050934,1.000000,1.000000,1.000000,1.000000,2.000000
P302,1441719.0,1.806525,0.395022,1.000000,2.000000,2.000000,2.000000,2.000000
AIT401,1441719.0,132.078816,47.000612,0.000000,148.803200,148.803200,148.808000,148.856100
AIT402,1441719.0,168.381924,27.527762,140.835700,154.114300,163.035100,176.826500,333.811800
FIT401,1441719.0,1.666928,0.274167,0.000000,1.701727,1.711595,1.721847,1.747862
LIT401,1441719.0,866.656499,130.992366,130.389600,835.439600,890.156400,934.914100,1003.935000
P401,1441719.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
P402,1441719.0,1.974555,0.157471,1.000000,2.000000,2.000000,2.000000,2.000000
P403,1441719.0,1.000042,0.006451,1.000000,1.000000,1.000000,1.000000,2.000000
P404,1441719.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
UV401,1441719.0,1.973631,0.160229,1.000000,2.000000,2.000000,2.000000,2.000000
AIT501,1441719.0,7.845262,0.072308,7.303769,7.824789,7.861318,7.886632,8.307037
AIT502,1441719.0,155.627059,17.233221,129.838500,144.501400,148.884900,169.110500,272.853100
AIT503,1441719.0,266.227020,5.748405,244.873100,262.528800,267.111000,270.059000,297.263500
AIT504,1441719.0,12.966362,8.039195,7.344271,11.266340,12.112280,13.304280,442.463500
FIT501,1441719.0,1.677749,0.271885,0.000000,1.710972,1.721738,1.731479,1.757754
FIT502,1441719.0,1.246903,0.202883,0.000000,1.262457,1.280902,1.292686,1.361983
FIT503,1441719.0,0.717580,0.116844,0.000000,0.732580,0.735269,0.741158,0.763691
FIT504,1441719.0,0.299553,0.049820,0.000000,0.306569,0.308106,0.308619,0.317010
P501,1441719.0,1.973482,0.160671,1.000000,2.000000,2.000000,2.000000,2.000000
P502,1441719.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
PIT501,1441719.0,245.368054,38.292541,8.891951,248.990600,251.297700,254.165600,264.643700
PIT502,1441719.0,1.131493,0.300181,0.000000,1.009195,1.105309,1.217441,3.668343
PIT503,1441719.0,185.642143,29.613455,3.108177,187.772400,189.935300,193.187600,200.637600
FIT601,1441719.0,0.015077,0.152257,0.000000,0.000000,0.000064,0.000128,1.802710
P601,1441719.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
P602,1441719.0,1.008294,0.090694,1.000000,1.000000,1.000000,1.000000,2.000000
P603,1441719.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
df.isnull().sum()

 Timestamp            0
FIT101                0
LIT101                0
 MV101           991800
P101                  0
P102                  0
 AIT201          991800
AIT202                0
AIT203                0
FIT201                0
 MV201           991800
 P201            991800
 P202            991800
P203                  0
 P204            991800
P205                  0
P206                  0
DPIT301               0
FIT301                0
LIT301                0
MV301                 0
MV302                 0
 MV303           991800
MV304                 0
P301                  0
P302                  0
AIT401                0
AIT402                0
FIT401                0
LIT401                0
P401                  0
P402                  0
P403                  0
P404                  0
UV401                 0
AIT501                0
AIT502                0
AIT503                0
AIT504                0
FIT501                0
FIT502                0
FIT503                0
FIT504                0
P501                  0
P502                  0
PIT501                0
PIT502                0
PIT503                0
FIT601                0
P601                  0
P602                  0
P603                  0
Normal/Attack         0
dtype: int64

In [8]:
df.columns.tolist()

[' Timestamp',
 'FIT101',
 'LIT101',
 ' MV101',
 'P101',
 'P102',
 ' AIT201',
 'AIT202',
 'AIT203',
 'FIT201',
 ' MV201',
 ' P201',
 ' P202',
 'P203',
 ' P204',
 'P205',
 'P206',
 'DPIT301',
 'FIT301',
 'LIT301',
 'MV301',
 'MV302',
 ' MV303',
 'MV304',
 'P301',
 'P302',
 'AIT401',
 'AIT402',
 'FIT401',
 'LIT401',
 'P401',
 'P402',
 'P403',
 'P404',
 'UV401',
 'AIT501',
 'AIT502',
 'AIT503',
 'AIT504',
 'FIT501',
 'FIT502',
 'FIT503',
 'FIT504',
 'P501',
 'P502',
 'PIT501',
 'PIT502',
 'PIT503',
 'FIT601',
 'P601',
 'P602',
 'P603',
 'Normal/Attack']

In [9]:
df.dtypes

 Timestamp        object
FIT101           float64
LIT101           float64
 MV101           float64
P101               int64
P102               int64
 AIT201          float64
AIT202           float64
AIT203           float64
FIT201           float64
 MV201           float64
 P201            float64
 P202            float64
P203               int64
 P204            float64
P205               int64
P206               int64
DPIT301          float64
FIT301           float64
LIT301           float64
MV301              int64
MV302              int64
 MV303           float64
MV304              int64
P301               int64
P302               int64
AIT401           float64
AIT402           float64
FIT401           float64
LIT401           float64
P401               int64
P402               int64
P403               int64
P404               int64
UV401              int64
AIT501           float64
AIT502           float64
AIT503           float64
AIT504           float64
FIT501           float64
FIT502           float64
FIT503           float64
FIT504           float64
P501               int64
P502               int64
PIT501           float64
PIT502           float64
PIT503           float64
FIT601           float64
P601               int64
P602               int64
P603               int64
Normal/Attack     object
dtype: object

# Initial Observations

## Dataset Summary

- Number of rows:
- Number of columns:
- Missing values:
- Target column:
- Timestamp column:
- Numeric features:
- Binary features:

---

## First Impression

Write your observations here...